"""add unique open engagement index

Revision ID: 9c33fc1e6822
Revises: f8df33f0c1e7
Create Date: 2026-10-03 21:34:22.195555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c33fc1e6822'
down_revision: Union[str, Sequence[str], None] = 'f8df33f0c1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_engagements_user_book_open', 'engagements', ['user_id', 'book_id'], unique=True, postgresql_where=sa.text("status IN ('tbr', 'reading', 'paused')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_engagements_user_book_open', table_name='engagements', postgresql_where=sa.text("status IN ('tbr', 'reading', 'paused')"))
    # ### end Alembic commands ###
