"""mark finish-generated progress logs

Revision ID: 9e68c17db8ec
Revises: 91b7c3e5a024
Create Date: 2026-09-01 01:03:31.155601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e68c17db8ec'
down_revision: Union[str, Sequence[str], None] = '91b7c3e5a024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "progress_logs",
        sa.Column("generated_by_finish", sa.Boolean(), nullable=True),
    )
    op.execute(
        "UPDATE progress_logs SET generated_by_finish = false"
    )
    op.alter_column(
        "progress_logs",
        "generated_by_finish",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progress_logs', 'generated_by_finish')
    # ### end Alembic commands ###
